### ISSUE TITLE
Feature Request : Add Client Methods for `get_filter_by` in Crouton-Client

### ISSUE THREAD

**Issue by RafaelJohn9** [swarmauri/crouton#6]
- Following implementing the `get_filter_by` endpoint in `Crouton`, new client methods are required in `Crouton-Client` to interact with this functionality. These methods will enable developers to use the `get_filter_by` functionality programmatically and take advantage of parameterized searches and pagination.

**Comment by cobycloud** [comment]
@RafaelJohn9 please verify the changes for this are complete

**Comment by RafaelJohn9** [comment]
@cobycloud This functionality has only been added to `SqlalchemyCRUDRouter`  so it's not  entirely complete

**Comment by cobycloud** [comment]
@RafaelJohn9 copy that. please create a ticket with a checklist for the remainder

**Comment by RafaelJohn9** [comment]
@cobycloud  will do :+1:
